title: 0xrh0d4m1n Notes
description: 0xrh0d4m1n hacking notes
baseurl: ''
username: 0xrh0d4m1n
typing_text: Security Researcher
email:
github_username: 0xrh0d4m1n
twitter_username: 0xrh0d4m1n

show_aboutme_card: false
show_skills_card: false
show_timeline_card: false
show_projects_card: true
show_projects: false

show_os_projects: true
os_projects_title: Open Source Projects

show_contact_card: true
contact_title: Contact
contact_description: Alright, if you want to send me a message, contact me through <a class="highlight-link" href="https://snort.social/p/0xrh0d4m1n@nostrplebs.com" target="_blank" rel="noreferrer"> Nostr </a>.

google-analytics:
  id: ''

plugins:
  - 'jekyll-github-metadata'

exclude:
  [
    '_assets',
    'Gemfile',
    'Gemfile.lock',
    'gulpfile.js',
    'node_modules',
    'package.json'
  ]
