authors:
  0xrh0d4m1n:
    name: 0xrh0d4m1n                                            # Author name
    description: Cyber Security Analyst                         # Author description
    avatar: https://avatars.githubusercontent.com/u/106601995   # Author avatar
    url: https://github.com/0xrh0d4m1n                          # Author website URL